In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
%matplotlib inline
from collections import Counter

import warnings
warnings.filterwarnings("ignore")

In [2]:
# load in CSV files
LoanStats = pd.read_csv("LoanStats.csv")
Lending_Data = pd.read_csv("lending_data.csv")
Lending_Data.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt loan_status  
0                5                 1       22800    low_risk  
1                3                 0       13600    low_risk  
2                3                 0       16100    low_risk  
3                5                 1       22700    low_risk  
4                5                 1       23000    low_risk

In [3]:
# Creating a Fit label for homeowner column
from sklearn.preprocessing import LabelEncoder
Label_Encoder=LabelEncoder()
Label_Encoder.fit(Lending_Data["homeowner"])
Lending_Data["homeowner"] = Label_Encoder.transform(Lending_Data["homeowner"])
Lending_Data.head()

loan_size  interest_rate  homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672          1            52800        0.431818   
1     8400.0          6.692          1            43600        0.311927   
2     9000.0          6.963          2            46100        0.349241   
3    10700.0          7.664          1            52700        0.430740   
4    10800.0          7.698          0            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt loan_status  
0                5                 1       22800    low_risk  
1                3                 0       13600    low_risk  
2                3                 0       16100    low_risk  
3                5                 1       22700    low_risk  
4                5                 1       23000    low_risk

In [4]:
# Create our features
X =Lending_Data.drop(columns="loan_status")

#create our target
Y=Lending_Data["loan_status"]
X

loan_size  interest_rate  homeowner  borrower_income  debt_to_income  \
0        10700.0          7.672          1            52800        0.431818   
1         8400.0          6.692          1            43600        0.311927   
2         9000.0          6.963          2            46100        0.349241   
3        10700.0          7.664          1            52700        0.430740   
4        10800.0          7.698          0            53000        0.433962   
...          ...            ...        ...              ...             ...   
77531    19100.0         11.261          1            86600        0.653580   
77532    17700.0         10.662          0            80900        0.629172   
77533    17600.0         10.595          2            80300        0.626401   
77534    16300.0         10.068          0            75300        0.601594   
77535    15600.0          9.742          0            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                    3                 0       16100  
3                    5                 1       22700  
4                    5                 1       23000  
...                ...               ...         ...  
77531               12                 2       56600  
77532               11                 2       50900  
77533               11                 2       50300  
77534               10                 2       45300  
77535                9                 2       42300  

[77536 rows x 8 columns]

In [5]:
X.describe()

loan_size  interest_rate     homeowner  borrower_income  \
count  77536.000000   77536.000000  77536.000000     77536.000000   
mean    9805.562577       7.292333      0.606144     49221.949804   
std     2093.223153       0.889495      0.667811      8371.635077   
min     5000.000000       5.250000      0.000000     30000.000000   
25%     8700.000000       6.825000      0.000000     44800.000000   
50%     9500.000000       7.172000      1.000000     48100.000000   
75%    10400.000000       7.528000      1.000000     51400.000000   
max    23800.000000      13.235000      2.000000    105200.000000   

       debt_to_income  num_of_accounts  derogatory_marks    total_debt  
count    77536.000000     77536.000000      77536.000000  77536.000000  
mean         0.377318         3.826610          0.392308  19221.949804  
std          0.081519         1.904426          0.582086   8371.635077  
min          0.000000         0.000000          0.000000      0.000000  
25%          0.330357         3.000000          0.000000  14800.000000  
50%          0.376299         4.000000          0.000000  18100.000000  
75%          0.416342         4.000000          1.000000  21400.000000  
max          0.714829        16.000000          3.000000  75200.000000

In [6]:
# Check the balance of our target values
Y.value_counts()

low_risk     75036
high_risk     2500
Name: loan_status, dtype: int64

In [17]:
# Create X_Train, X_Test, Y_Train, Y_Test
from sklearn.model_selection import train_test_split

X_Train, X_Test, Y_Train, Y_Test= train_test_split(X, Y, random_state=1, stratify=Y)
X_Train.shape

(58152, 8)

In [8]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()

In [9]:
#Fit the Standard Scaler with the training data
X_Scaler = Scaler.fit(X_Train)

In [14]:
# Scale the training and testing data
X_Train_Scaled = X_Scaler.transform(X_Train)
X_Test_Scaled = X_Scaler.transform(X_Test)
X_Test_Scaled

array([[ 0.80958089,  0.81480327,  0.59151332, ...,  0.61664652,
         1.04495557,  0.80977921],
       [-0.05072219, -0.07373693, -0.90997878, ...,  0.09115188,
        -0.67471435, -0.07456551],
       [ 3.39049014,  3.39606878,  0.59151332, ...,  3.24411968,
         2.76462549,  3.39110974],
       ...,
       [ 0.57060781,  0.58423271,  0.59151332, ...,  0.61664652,
         1.04495557,  0.58271773],
       [ 0.61840243,  0.63484576, -0.90997878, ...,  0.61664652,
         1.04495557,  0.63052015],
       [ 0.18825089,  0.18045305, -0.90997878, ...,  0.09115188,
         1.04495557,  0.17639718]])

In [21]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver = 'lbfgs', random_state=1)
model.fit(X_Train_Scaled, Y_Train)

LogisticRegression(random_state=1)

In [22]:
# Calculate the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_Test_Scaled)
balanced_accuracy_score(Y_Test, y_pred)

0.9892813049736127

In [24]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_Test, y_pred)

array([[  615,    10],
       [  102, 18657]])

In [25]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(Y_Test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.86      0.98      0.99      0.92      0.99      0.98       625
   low_risk       1.00      0.99      0.98      1.00      0.99      0.98     18759

avg / total       0.99      0.99      0.98      0.99      0.99      0.98     19384



In [42]:
# Oversampling
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler

Random_Over_Sampler = RandomOverSampler()
X_Random_Resample, Y_Random_Resample = Random_Over_Sampler.fit_resample(X_Train_Scaled, Y_Train)

In [43]:
# View the count of target classes with Counter
Counter(Y_Random_Resample)

Counter({'low_risk': 56277, 'high_risk': 56277})

In [44]:
# Train the Logistic Regression model using the resampled data
model_Random_Over_Sampler = LogisticRegression(solver = 'lbfgs', random_state=1)
model_Random_Over_Sampler.fit(X_Random_Resample, Y_Random_Resample)

LogisticRegression(random_state=1)

In [45]:
# Calculated the balanced accuracy score

y_Random_Over_Sample_pred = model_Random_Over_Sampler.predict(X_Test_Scaled)
balanced_accuracy_score(Y_Test, y_Random_Over_Sample_pred)

0.9946414201183431

In [46]:
# Display the confusion matrix
confusion_matrix(Y_Test, y_Random_Over_Sample_pred)

array([[  622,     3],
       [  111, 18648]])

In [47]:
# Print the imbalanced classification report
print(classification_report_imbalanced(Y_Test, y_Random_Over_Sample_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      1.00      0.99      0.92      0.99      0.99       625
   low_risk       1.00      0.99      1.00      1.00      0.99      0.99     18759

avg / total       0.99      0.99      1.00      0.99      0.99      0.99     19384



In [49]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
Oversample = SMOTE() 
X_SMOTE, Y_SMOTE = Oversample.fit_resample(X_Train_Scaled,Y_Train)


In [50]:
# View the count of target classes with Counter
Counter(Y_SMOTE)

Counter({'low_risk': 56277, 'high_risk': 56277})

In [51]:
# Train the Logistic Regression model using the resampled data
model_SMOTE = LogisticRegression(solver = 'lbfgs', random_state=1)
model_SMOTE.fit(X_SMOTE, Y_SMOTE)

LogisticRegression(random_state=1)

In [53]:
# Calculate the balanced accuracy score

y_SMOTE_pred = model_SMOTE.predict(X_Test_Scaled)
balanced_accuracy_score(Y_Test, y_SMOTE_pred)

0.9946414201183431

In [54]:
# Display the confusion matrix
confusion_matrix(Y_Test, y_SMOTE_pred)

array([[  622,     3],
       [  111, 18648]])

In [55]:
# Print the imbalanced classification report
print(classification_report_imbalanced(Y_Test, y_SMOTE_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      1.00      0.99      0.92      0.99      0.99       625
   low_risk       1.00      0.99      1.00      1.00      0.99      0.99     18759

avg / total       0.99      0.99      1.00      0.99      0.99      0.99     19384



In [58]:
# UNDERSAMPLING
# Resample the data using the ClusterCentroids resampler

from imblearn.under_sampling import ClusterCentroids
Under_Sample_CC = ClusterCentroids()
X_Under_Sample_CC, Y_Under_Sample_CC = Under_Sample_CC.fit_resample(X_Train_Scaled, Y_Train)

In [60]:
# View the count of target classes with Counter
Counter(Y_Under_Sample_CC)

Counter({'high_risk': 1875, 'low_risk': 1875})

In [61]:
# Train the Logistic Regression model using the resampled data
model_ClusterCentroids = LogisticRegression(solver = 'lbfgs', random_state=1)
model_ClusterCentroids.fit(X_Under_Sample_CC, Y_Under_Sample_CC)

LogisticRegression(random_state=1)

In [66]:
# Calculate the balanced accuracy score
y_ClusterCentroids_pred = model_ClusterCentroids.predict(X_Test_Scaled)
balanced_accuracy_score(Y_Test, y_ClusterCentroids_pred)

0.9932813049736127

In [67]:
# Display the confusion matrix
confusion_matrix(Y_Test, y_ClusterCentroids_pred)

array([[  620,     5],
       [  102, 18657]])

In [68]:
# Print the imbalanced classification report
print(classification_report_imbalanced(Y_Test, y_ClusterCentroids_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.86      0.99      0.99      0.92      0.99      0.99       625
   low_risk       1.00      0.99      0.99      1.00      0.99      0.99     18759

avg / total       1.00      0.99      0.99      0.99      0.99      0.99     19384



In [74]:
#COMBINATION (Over and Under Sampling)
from imblearn.combine import SMOTEENN
Combine_SMOTEENN = SMOTEENN()
X_SMOTEENN, Y_SMOTEENN = Combine_SMOTEENN.fit_resample(X_Train_Scaled, Y_Train)

In [75]:
# View the count of target classes with Counter
Counter(Y_SMOTEENN)

Counter({'high_risk': 55686, 'low_risk': 55919})

In [77]:
# Train the Logistic Regression model using the resampled data
model_SMOTEENN = LogisticRegression(solver = 'lbfgs', random_state=1)
model_SMOTEENN.fit(X_SMOTEENN, Y_SMOTEENN)

LogisticRegression(random_state=1)

In [78]:
# Calculate the balanced accuracy score
y_SMOTEENN_pred = model_SMOTEENN.predict(X_Test_Scaled)
balanced_accuracy_score(Y_Test, y_SMOTEENN_pred)

0.9946414201183431

In [79]:
# Display the confusion matrix
confusion_matrix(Y_Test, y_SMOTEENN_pred)

array([[  622,     3],
       [  111, 18648]])

In [80]:
# Print the imbalanced classification report
print(classification_report_imbalanced(Y_Test, y_SMOTEENN_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      1.00      0.99      0.92      0.99      0.99       625
   low_risk       1.00      0.99      1.00      1.00      0.99      0.99     18759

avg / total       0.99      0.99      1.00      0.99      0.99      0.99     19384



In [81]:
# Final Questions
#1. Which model had the best balanced accuracy score?
#2. Which model had the best recall score?
#3. Which model had the best geometric mean score?

In [82]:
Results = open('results.txt', 'w')

In [83]:
Results.write(f" 1. The SMOTE, SMOTEENN, and Oversampling models all had the best balaced accuracy score.\n")
Results.write(f" 2. THE SMOTE, SMOTEEN, and Oversampling models had the best Recall scores.\n")
Results.write(f" 3. All models produced the same geometric mean score.")

54

In [84]:
Results.close()